import sqlite3

DB_PATH = "/data/flashcards.db"

words = {
    "ihminen": "person, human",
    "mies": "man",
    "nainen": "woman",
    "lapsi": "child",
    "perhe": "family",
    "ystävä": "friend",
    "opiskelija": "student",
    "koti": "home",
    "kaupunki": "city, town",
    "maa": "country, land, ground",
    "kieli": "language, tongue",
    "kirja": "book",
    "pöytä": "table",
    "tuoli": "chair",
    "ovi": "door",
    "ikkuna": "window",
    "puhelin": "phone",
    "raha": "money",
    "aika": "time",
    "päivä": "day",
    "viikko": "week",
    "vuosi": "year",
    "vesi": "water",
    "ruoka": "food",
    "kahvi": "coffee",
    "olut": "beer",
    "bussi": "bus",
    "juna": "train",
    "auto": "car",
    "koulu": "school",
    "työ": "work, job",
    "huone": "room",
    "nimi": "name",
    "aamu": "morning",
    "ilta": "evening",
    "yö": "night",
    "lounas": "lunch",
    "aamiainen": "breakfast",
    "illallinen": "dinner",
    "sää": "weather",
    "katu": "street",
    "ranta": "beach, shore",
    "kello": "clock, watch",
    "olla": "to be",
    "puhua": "to speak",
    "asua": "to live, to reside",
    "mennä": "to go",
    "tulla": "to come",
    "tehdä": "to do, to make",
    "tietää": "to know (a fact)",
    "tuntea": "to know (a person/feeling)",
    "nähdä": "to see",
    "kuulla": "to hear",
    "syödä": "to eat",
    "juoda": "to drink",
    "lukea": "to read",
    "kirjoittaa": "to write",
    "haluta": "to want",
    "tarvita": "to need",
    "pitää": "to like, to hold",
    "tykätä": "to like (often used instead of pitää)",
    "ostaa": "to buy",
    "myydä": "to sell",
    "sanoa": "to say",
    "kysyä": "to ask",
    "vastata": "to answer",
    "odottaa": "to wait",
    "nukkua": "to sleep",
    "herätä": "to wake up",
    "matkustaa": "to travel",
    "oppia": "to learn",
    "opettaa": "to teach",
    "maksaa": "to pay, to cost",
    "ymmärtää": "to understand",
    "nauttia": "to enjoy",
    "soittaa": "to call, to play (an instrument)",
    "iso": "big",
    "pieni": "small",
    "hyvä": "good",
    "huono": "bad",
    "uusi": "new",
    "vanha": "old",
    "kaunis": "beautiful",
    "ruma": "ugly",
    "kylmä": "cold",
    "lämmin": "warm",
    "kuuma": "hot",
    "kallis": "expensive",
    "halpa": "cheap",
    "nopea": "fast",
    "hidas": "slow",
    "iloinen": "happy, joyful",
    "surullinen": "sad",
    "helppo": "easy",
    "vaikea": "difficult",
    "pitkä": "long, tall",
    "lyhyt": "short",
    "puhdas": "clean",
    "likainen": "dirty",
    "vapaa": "free, available",
    "varattu": "busy, reserved",
    "avoin": "open",
    "suljettu": "closed",
    "minä": "I",
    "sinä": "you (singular, informal)",
    "hän": "he, she, it",
    "me": "we",
    "te": "you (plural, formal)",
    "he": "they",
    "se": "it (non-person)",
    "tämä": "this",
    "tuo": "that (closer)",
    "mikä": "what",
    "kuka": "who",
    "minun": "my",
    "sinun": "your (singular)",
    "meidän": "our",
    "teidän": "your (plural)",
    "kaikki": "all, everyone",
    "joku": "someone, somebody",
    "ei kukaan": "nobody",
    "nolla": "zero (0)",
    "yksi": "one (1)",
    "kaksi": "two (2)",
    "kolme": "three (3)",
    "neljä": "four (4)",
    "viisi": "five (5)",
    "kuusi": "six (6)",
    "seitsemän": "seven (7)",
    "kahdeksan": "eight (8)",
    "yhdeksän": "nine (9)",
    "kymmenen": "ten (10)",
    "tässä": "here, in here",
    "siellä": "there",
    "nyt": "now",
    "sitten": "then, afterwards",
    "tänään": "today",
    "eilen": "yesterday",
    "huomenna": "tomorrow",
    "aina": "always",
    "koskaan": "never (used with negative verb)",
    "usein": "often",
    "harvoin": "rarely",
    "hyvin": "well",
    "huonosti": "poorly",
    "paljon": "much, a lot",
    "vähän": "a little, few",
    "ehkä": "maybe, perhaps",
    "tietysti": "of course",
    "kiitos": "thank you",
    "ole hyvä": "you're welcome, please",
    "anteeksi": "excuse me, sorry",
    "Milloin?": "When?",
    "Tänne": "to here (directional)",
    "Tuonne": "to there (directional)",
    "sisällä": "inside",
    "ulkona": "outside",
    "päällä": "on top of",
    "alla": "under",
    "vieressä": "next to",
    "edessä": "in front of",
    "takana": "behind",
    "kanssa": "with",
    "ilman": "without",
    "ennen": "before",
    "jälkeen": "after",
    "ja": "and",
    "tai": "or",
    "mutta": "but",
    "että": "that (conjunction)",
    "koska": "because",
    "jos": "if",
    "myös": "also",
    "vain": "only",
    "ei": "no, not (negative verb root)",
    "joo / kyllä": "yes",
    "hei": "hi, hello",
    "moikka": "bye (informal)",
    "Hyvää huomenta": "Good morning",
    "Hyvää päivää": "Good day",
    "Hyvää iltaa": "Good evening",
    "Hyvää yötä": "Good night",
    "Hauska tutustua": "Nice to meet you",
    "Mitä kuuluu?": "How are you?",
    "Kiitos, hyvää": "Fine, thanks",
    "Näkemiin": "Goodbye (formal)",
    "Tervetuloa": "Welcome",
    "Onko sinulla...?": "Do you have...?",
    "Minulla on": "I have",
    "Minulla ei ole": "I don't have",
    "Paljonko se maksaa?": "How much does it cost?",
    "Saanko laskun?": "May I have the bill?",
    "Mistä olet kotoisin?": "Where are you from?",
    "Olen kotoisin...": "I am from...",
    "Hyvää ruokahalua": "Enjoy your meal",
    "Anteeksi, en ymmärrä": "Sorry, I don't understand",
    "Puhutko englantia?": "Do you speak English?",
    "Voin auttaa": "I can help",
    "Ei se mitään": "It doesn't matter, no worries",
    "Minä rakastan sinua": "I love you",
    "Onnea!": "Good luck! / Congratulations!",
    "Mitä kello on?": "What time is it?",
    "punainen": "red",
    "sininen": "blue",
    "keltainen": "yellow",
    "vihreä": "green",
    "musta": "black",
    "valkoinen": "white",
    "harmaa": "gray",
    "ruskea": "brown",
    "oranssi": "orange",
    "violetti": "purple",
    "herätä": "to wake up",
    "pestä": "to wash",
    "pukeutua": "to get dressed",
    "käydä kaupassa": "to go grocery shopping",
    "laittaa ruokaa": "to cook food",
    "siivota": "to clean (house)",
    "katsoa": "to watch, to look at",
    "kuunnella": "to listen",
    "levätä": "to rest",
    "auttaa": "to help",
    "hymyillä": "to smile",
    "itkeä": "to cry",
    "juosta": "to run",
    "kävellä": "to walk",
    "istua": "to sit",
    "seisoa": "to stand",
    "nukkua": "to sleep",
    "asia": "thing, matter",
    "tapa": "way, custom, manner",
    "paikka": "place, location",
    "hetki": "moment",
    "elämä": "life",
    "kuolema": "death",
    "luonto": "nature",
    "ongelma": "problem",
    "ratkaisu": "solution",
    "sota": "war",
    "rauha": "peace",
    "tunne": "feeling, emotion",
    "tieto": "information, knowledge",
    "taito": "skill",
    "nyt": "now",
    "sitten": "then, afterwards",
    "ennen": "before",
    "jälkeen": "after",
    "pian": "soon",
    "myöhemmin": "later",
    "heti": "immediately",
    "joskus": "sometimes",
    "viimeinen": "last, final",
    "ensin": "first (in order)",
    "tunti": "hour",
    "minuutti": "minute",
    "sekunti": "second",
    "aamulla": "in the morning",
    "illalla": "in the evening",
    "samanlainen": "similar",
    "erilainen": "different",
    "tarpeeksi": "enough",
    "liikaa": "too much",
    "monta": "many",
    "muutamia": "a few",
    "molemmat": "both",
    "jotain": "something",
    "ei mitään": "nothing",
    "toinen": "other, second",
    "leipä": "bread",
    "maito": "milk",
    "juusto": "cheese",
    "liha": "meat",
    "kala": "fish",
    "hedelmä": "fruit",
    "vihannes": "vegetable",
    "suola": "salt",
    "sokeri": "sugar"
}

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

for front, back in words.items():
    cursor.execute("INSERT INTO flashcards (user_id, front, back, box) VALUES (?, ?, ?, ?)", (0, front, back, 1))

conn.commit()
conn.close()

print("Database seeded with Finnish words!")
